# Directory to parse
source: assets

# Directory to build the styleguide
destination: styleguide

# Hologram theme
documentation_assets: bower_components/Cortana
custom_markdown: bower_components/Cortana/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README

dependencies:
  - build/js
  - build/css
  - build/img
  - build/fonts

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
# - 'css/vendors.css'
  - 'css/main.css'

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'js/vendors.min.js'
  - 'js/main.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '